### ISSUE TITLE
Adding notification banner for recording

### ISSUE THREAD

**Issue by Cole-Allen** [EZ64cool/obs-hadowplay#10]
Would it be possible to add a banner notification for when you trigger the saved replay with hotkeys? Right now I need to check the folder to see if it saved

**Comment by EZ64cool** [comment]
Yeah that definitely sounds like a good idea as I've also found this to be annoying at times. I'm going to look into adding Windows toast notifications if possible (unsure if I can do it at the plugin level).

**Comment by EZ64cool** [comment]
After some testing it looks promising 👍 
Starting work in save_notification branch

**Comment by scorthyn** [comment]
This is a great idea! For now I'm using this addon with [OBS Notifier ](https://github.com/DmitriySalnikov/OBSNotifier) and it works exactly like Nvidia shadowplay, even better since theres notifications when the mic is off or on. Would be awesome to have everything integrated tho :D, this addon is already indispensable

**Comment by EZ64cool** [comment]
This should now be avaliable in [1.1.4-beta](https://github.com/EZ64cool/obs-hadowplay/releases/tag/1.1.4-beta) for testing.
Unfortunately the option I went with ended up having less functionality than I'd liked, but it does what's expected.
