### ISSUE TITLE
Replay buffer not running in The Finals

### ISSUE THREAD

**Issue by WatislavB** [EZ64cool/obs-hadowplay#17]
Hello! 👋

I've encountered a situation where the replay buffer is not turned on. I used v1.2.1 beta and it works in Deep Rock Galactic (process name "FSD-Win64-Shipping.exe") and Overwatch 2 for example, but does not work in The Finals (process name "Discovery.exe"). The Finals is captured by game_capture, but the replay buffer is not triggered. Could you take a look and try to figure it out? 🙏

[2024-03-27 09-25-17.txt](https://github.com/EZ64cool/obs-hadowplay/files/14769114/2024-03-27.09-25-17.txt)

**Comment by WatislavB** [comment]
To make it clearer, in this report I launched Overwatch 2, The Finals and Deep Rock Galactic sequentially, but it is on The Finals that the replay buffer does not start automatically

**Comment by EZ64cool** [comment]
Hmm, so looking at the log you posted it looks like it was never able to hook into The Finals and so that's why the replay buffer never started.
`09:30:31.501: [game-capture: 'Захват игры'] attempting to hook fullscreen process: Discovery.exe
09:30:31.518: [game-capture: 'Захват игры'] capture stopped
09:30:51.585: [game-capture: 'Захват игры'] attempting to hook fullscreen process: Discovery.exe
09:30:51.602: [game-capture: 'Захват игры'] capture stopped
09:30:55.601: [game-capture: 'Захват игры'] attempting to hook fullscreen process: Discovery.exe
09:30:55.618: [game-capture: 'Захват игры'] capture stopped
09:30:59.618: [game-capture: 'Захват игры'] attempting to hook fullscreen process: Discovery.exe
09:30:59.635: [game-capture: 'Захват игры'] capture stopped`

I did a quick google and it looks like some other people have run into a similar issue
https://www.reddit.com/r/obs/comments/18im267/the_finals_black_screen_with_game_capture/

Can you confirm that The Finals is actually visible within obs whilst the replay buffer hasn't started?

**Comment by WatislavB** [comment]
The game is being updated right now. But as far as I remember, the game was captured, but I have both game_capture and monitor_capture on the stage, so I’m not sure if it was game_capture. At the same time, I deliberately did not minimize the game at startup, so as not to interfere with the game capture. As soon as the update is completed, I will test it again and clarify

**Comment by WatislavB** [comment]
Indeed, when recording game_capture, I only see a black screen. It seems the problem is with the game itself. Sorry to bother you

**Comment by WatislavB** [comment]
I'd like to add that The Finals capture seems to be working great right now. It seems the problem was in MSI Afterburner (or rather RivaTuner). I fixed this using the Microsoft Detours API in Settings. This also fixed Valorant's capture for me. 😅
